GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/active

###
GET http://localhost:3000/api/users/3

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "",
  "lastName": "Lino"
}

###

DELETE http://localhost:3000/api/users/8

###

PATCH  http://localhost:3000/api/users/3
Content-Type: application/json

{
  "firstName": "Gonzalo",
  "lastName": "Plata"
}

###
PATCH  http://localhost:3000/api/users/4/toggle