GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Marco Aurelio",
  "lastName": "Hansen"
}

###

DELETE http://localhost:3000/api/users/2

###

PATCH  http://localhost:3000/api/users/3
Content-Type: application/json

{
  "firstName": "Marco Aurelio",
  "lastName": "Hansen"
}